/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDbv0_0_39_clusters_info.h
 *
 * 
 */

#ifndef OAIDbv0_0_39_clusters_info_H
#define OAIDbv0_0_39_clusters_info_H

#include <QJsonObject>

#include "OAIDbv0_0_39_error.h"
#include "OAIDbv0_0_39_meta.h"
#include "OAIDbv0_0_39_warning.h"
#include "OAIV0_0_39_cluster_rec.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIDbv0_0_39_meta;
class OAIDbv0_0_39_error;
class OAIDbv0_0_39_warning;
class OAIV0_0_39_cluster_rec;

class OAIDbv0_0_39_clusters_info : public OAIObject {
public:
    OAIDbv0_0_39_clusters_info();
    OAIDbv0_0_39_clusters_info(QString json);
    ~OAIDbv0_0_39_clusters_info() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIDbv0_0_39_meta getMeta() const;
    void setMeta(const OAIDbv0_0_39_meta &meta);
    bool is_meta_Set() const;
    bool is_meta_Valid() const;

    QList<OAIDbv0_0_39_error> getErrors() const;
    void setErrors(const QList<OAIDbv0_0_39_error> &errors);
    bool is_errors_Set() const;
    bool is_errors_Valid() const;

    QList<OAIDbv0_0_39_warning> getWarnings() const;
    void setWarnings(const QList<OAIDbv0_0_39_warning> &warnings);
    bool is_warnings_Set() const;
    bool is_warnings_Valid() const;

    QList<OAIV0_0_39_cluster_rec> getClusters() const;
    void setClusters(const QList<OAIV0_0_39_cluster_rec> &clusters);
    bool is_clusters_Set() const;
    bool is_clusters_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIDbv0_0_39_meta m_meta;
    bool m_meta_isSet;
    bool m_meta_isValid;

    QList<OAIDbv0_0_39_error> m_errors;
    bool m_errors_isSet;
    bool m_errors_isValid;

    QList<OAIDbv0_0_39_warning> m_warnings;
    bool m_warnings_isSet;
    bool m_warnings_isValid;

    QList<OAIV0_0_39_cluster_rec> m_clusters;
    bool m_clusters_isSet;
    bool m_clusters_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIDbv0_0_39_clusters_info)

#endif // OAIDbv0_0_39_clusters_info_H
