/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_41_openapi_users_add_cond_resp_str.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_41_openapi_users_add_cond_resp_str::OAIV0_0_41_openapi_users_add_cond_resp_str(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_41_openapi_users_add_cond_resp_str::OAIV0_0_41_openapi_users_add_cond_resp_str() {
    this->initializeModel();
}

OAIV0_0_41_openapi_users_add_cond_resp_str::~OAIV0_0_41_openapi_users_add_cond_resp_str() {}

void OAIV0_0_41_openapi_users_add_cond_resp_str::initializeModel() {

    m_added_users_isSet = false;
    m_added_users_isValid = false;

    m_meta_isSet = false;
    m_meta_isValid = false;

    m_errors_isSet = false;
    m_errors_isValid = false;

    m_warnings_isSet = false;
    m_warnings_isValid = false;
}

void OAIV0_0_41_openapi_users_add_cond_resp_str::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_41_openapi_users_add_cond_resp_str::fromJsonObject(QJsonObject json) {

    m_added_users_isValid = ::OpenAPI::fromJsonValue(m_added_users, json[QString("added_users")]);
    m_added_users_isSet = !json[QString("added_users")].isNull() && m_added_users_isValid;

    m_meta_isValid = ::OpenAPI::fromJsonValue(m_meta, json[QString("meta")]);
    m_meta_isSet = !json[QString("meta")].isNull() && m_meta_isValid;

    m_errors_isValid = ::OpenAPI::fromJsonValue(m_errors, json[QString("errors")]);
    m_errors_isSet = !json[QString("errors")].isNull() && m_errors_isValid;

    m_warnings_isValid = ::OpenAPI::fromJsonValue(m_warnings, json[QString("warnings")]);
    m_warnings_isSet = !json[QString("warnings")].isNull() && m_warnings_isValid;
}

QString OAIV0_0_41_openapi_users_add_cond_resp_str::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_41_openapi_users_add_cond_resp_str::asJsonObject() const {
    QJsonObject obj;
    if (m_added_users_isSet) {
        obj.insert(QString("added_users"), ::OpenAPI::toJsonValue(m_added_users));
    }
    if (m_meta.isSet()) {
        obj.insert(QString("meta"), ::OpenAPI::toJsonValue(m_meta));
    }
    if (m_errors.size() > 0) {
        obj.insert(QString("errors"), ::OpenAPI::toJsonValue(m_errors));
    }
    if (m_warnings.size() > 0) {
        obj.insert(QString("warnings"), ::OpenAPI::toJsonValue(m_warnings));
    }
    return obj;
}

QString OAIV0_0_41_openapi_users_add_cond_resp_str::getAddedUsers() const {
    return m_added_users;
}
void OAIV0_0_41_openapi_users_add_cond_resp_str::setAddedUsers(const QString &added_users) {
    m_added_users = added_users;
    m_added_users_isSet = true;
}

bool OAIV0_0_41_openapi_users_add_cond_resp_str::is_added_users_Set() const{
    return m_added_users_isSet;
}

bool OAIV0_0_41_openapi_users_add_cond_resp_str::is_added_users_Valid() const{
    return m_added_users_isValid;
}

OAIV0_0_41_openapi_shares_resp_meta OAIV0_0_41_openapi_users_add_cond_resp_str::getMeta() const {
    return m_meta;
}
void OAIV0_0_41_openapi_users_add_cond_resp_str::setMeta(const OAIV0_0_41_openapi_shares_resp_meta &meta) {
    m_meta = meta;
    m_meta_isSet = true;
}

bool OAIV0_0_41_openapi_users_add_cond_resp_str::is_meta_Set() const{
    return m_meta_isSet;
}

bool OAIV0_0_41_openapi_users_add_cond_resp_str::is_meta_Valid() const{
    return m_meta_isValid;
}

QList<OAIV0_0_41_openapi_shares_resp_errors_inner> OAIV0_0_41_openapi_users_add_cond_resp_str::getErrors() const {
    return m_errors;
}
void OAIV0_0_41_openapi_users_add_cond_resp_str::setErrors(const QList<OAIV0_0_41_openapi_shares_resp_errors_inner> &errors) {
    m_errors = errors;
    m_errors_isSet = true;
}

bool OAIV0_0_41_openapi_users_add_cond_resp_str::is_errors_Set() const{
    return m_errors_isSet;
}

bool OAIV0_0_41_openapi_users_add_cond_resp_str::is_errors_Valid() const{
    return m_errors_isValid;
}

QList<OAIV0_0_41_openapi_shares_resp_warnings_inner> OAIV0_0_41_openapi_users_add_cond_resp_str::getWarnings() const {
    return m_warnings;
}
void OAIV0_0_41_openapi_users_add_cond_resp_str::setWarnings(const QList<OAIV0_0_41_openapi_shares_resp_warnings_inner> &warnings) {
    m_warnings = warnings;
    m_warnings_isSet = true;
}

bool OAIV0_0_41_openapi_users_add_cond_resp_str::is_warnings_Set() const{
    return m_warnings_isSet;
}

bool OAIV0_0_41_openapi_users_add_cond_resp_str::is_warnings_Valid() const{
    return m_warnings_isValid;
}

bool OAIV0_0_41_openapi_users_add_cond_resp_str::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_added_users_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_meta.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_errors.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_warnings.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_41_openapi_users_add_cond_resp_str::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_added_users_isValid && true;
}

} // namespace OpenAPI
