/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_40_user_default.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace hm:slurm:client {

OAIV0_0_40_user_default::OAIV0_0_40_user_default(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_40_user_default::OAIV0_0_40_user_default() {
    this->initializeModel();
}

OAIV0_0_40_user_default::~OAIV0_0_40_user_default() {}

void OAIV0_0_40_user_default::initializeModel() {

    m_account_isSet = false;
    m_account_isValid = false;

    m_wckey_isSet = false;
    m_wckey_isValid = false;
}

void OAIV0_0_40_user_default::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_40_user_default::fromJsonObject(QJsonObject json) {

    m_account_isValid = ::hm:slurm:client::fromJsonValue(m_account, json[QString("account")]);
    m_account_isSet = !json[QString("account")].isNull() && m_account_isValid;

    m_wckey_isValid = ::hm:slurm:client::fromJsonValue(m_wckey, json[QString("wckey")]);
    m_wckey_isSet = !json[QString("wckey")].isNull() && m_wckey_isValid;
}

QString OAIV0_0_40_user_default::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_40_user_default::asJsonObject() const {
    QJsonObject obj;
    if (m_account_isSet) {
        obj.insert(QString("account"), ::hm:slurm:client::toJsonValue(m_account));
    }
    if (m_wckey_isSet) {
        obj.insert(QString("wckey"), ::hm:slurm:client::toJsonValue(m_wckey));
    }
    return obj;
}

QString OAIV0_0_40_user_default::getAccount() const {
    return m_account;
}
void OAIV0_0_40_user_default::setAccount(const QString &account) {
    m_account = account;
    m_account_isSet = true;
}

bool OAIV0_0_40_user_default::is_account_Set() const{
    return m_account_isSet;
}

bool OAIV0_0_40_user_default::is_account_Valid() const{
    return m_account_isValid;
}

QString OAIV0_0_40_user_default::getWckey() const {
    return m_wckey;
}
void OAIV0_0_40_user_default::setWckey(const QString &wckey) {
    m_wckey = wckey;
    m_wckey_isSet = true;
}

bool OAIV0_0_40_user_default::is_wckey_Set() const{
    return m_wckey_isSet;
}

bool OAIV0_0_40_user_default::is_wckey_Valid() const{
    return m_wckey_isValid;
}

bool OAIV0_0_40_user_default::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_account_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_wckey_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_40_user_default::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace hm:slurm:client
