/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_39_step_tres.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_39_step_tres::OAIV0_0_39_step_tres(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_39_step_tres::OAIV0_0_39_step_tres() {
    this->initializeModel();
}

OAIV0_0_39_step_tres::~OAIV0_0_39_step_tres() {}

void OAIV0_0_39_step_tres::initializeModel() {

    m_allocated_isSet = false;
    m_allocated_isValid = false;
}

void OAIV0_0_39_step_tres::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_39_step_tres::fromJsonObject(QJsonObject json) {

    m_allocated_isValid = ::OpenAPI::fromJsonValue(m_allocated, json[QString("allocated")]);
    m_allocated_isSet = !json[QString("allocated")].isNull() && m_allocated_isValid;
}

QString OAIV0_0_39_step_tres::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_39_step_tres::asJsonObject() const {
    QJsonObject obj;
    if (m_allocated.size() > 0) {
        obj.insert(QString("allocated"), ::OpenAPI::toJsonValue(m_allocated));
    }
    return obj;
}

QList<OAIV0_0_39_tres> OAIV0_0_39_step_tres::getAllocated() const {
    return m_allocated;
}
void OAIV0_0_39_step_tres::setAllocated(const QList<OAIV0_0_39_tres> &allocated) {
    m_allocated = allocated;
    m_allocated_isSet = true;
}

bool OAIV0_0_39_step_tres::is_allocated_Set() const{
    return m_allocated_isSet;
}

bool OAIV0_0_39_step_tres::is_allocated_Valid() const{
    return m_allocated_isValid;
}

bool OAIV0_0_39_step_tres::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_allocated.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_39_step_tres::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
