/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_39_step_CPU_requested_frequency.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_39_step_CPU_requested_frequency::OAIV0_0_39_step_CPU_requested_frequency(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_39_step_CPU_requested_frequency::OAIV0_0_39_step_CPU_requested_frequency() {
    this->initializeModel();
}

OAIV0_0_39_step_CPU_requested_frequency::~OAIV0_0_39_step_CPU_requested_frequency() {}

void OAIV0_0_39_step_CPU_requested_frequency::initializeModel() {

    m_min_isSet = false;
    m_min_isValid = false;

    m_max_isSet = false;
    m_max_isValid = false;
}

void OAIV0_0_39_step_CPU_requested_frequency::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_39_step_CPU_requested_frequency::fromJsonObject(QJsonObject json) {

    m_min_isValid = ::OpenAPI::fromJsonValue(m_min, json[QString("min")]);
    m_min_isSet = !json[QString("min")].isNull() && m_min_isValid;

    m_max_isValid = ::OpenAPI::fromJsonValue(m_max, json[QString("max")]);
    m_max_isSet = !json[QString("max")].isNull() && m_max_isValid;
}

QString OAIV0_0_39_step_CPU_requested_frequency::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_39_step_CPU_requested_frequency::asJsonObject() const {
    QJsonObject obj;
    if (m_min.isSet()) {
        obj.insert(QString("min"), ::OpenAPI::toJsonValue(m_min));
    }
    if (m_max.isSet()) {
        obj.insert(QString("max"), ::OpenAPI::toJsonValue(m_max));
    }
    return obj;
}

OAIV0_0_39_uint32_no_val OAIV0_0_39_step_CPU_requested_frequency::getMin() const {
    return m_min;
}
void OAIV0_0_39_step_CPU_requested_frequency::setMin(const OAIV0_0_39_uint32_no_val &min) {
    m_min = min;
    m_min_isSet = true;
}

bool OAIV0_0_39_step_CPU_requested_frequency::is_min_Set() const{
    return m_min_isSet;
}

bool OAIV0_0_39_step_CPU_requested_frequency::is_min_Valid() const{
    return m_min_isValid;
}

OAIV0_0_39_uint32_no_val OAIV0_0_39_step_CPU_requested_frequency::getMax() const {
    return m_max;
}
void OAIV0_0_39_step_CPU_requested_frequency::setMax(const OAIV0_0_39_uint32_no_val &max) {
    m_max = max;
    m_max_isSet = true;
}

bool OAIV0_0_39_step_CPU_requested_frequency::is_max_Set() const{
    return m_max_isSet;
}

bool OAIV0_0_39_step_CPU_requested_frequency::is_max_Valid() const{
    return m_max_isValid;
}

bool OAIV0_0_39_step_CPU_requested_frequency::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_min.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_max.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_39_step_CPU_requested_frequency::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
