/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_40_reservation_core_spec.h
 *
 * 
 */

#ifndef OAIV0_0_40_reservation_core_spec_H
#define OAIV0_0_40_reservation_core_spec_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIV0_0_40_reservation_core_spec : public OAIObject {
public:
    OAIV0_0_40_reservation_core_spec();
    OAIV0_0_40_reservation_core_spec(QString json);
    ~OAIV0_0_40_reservation_core_spec() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getNode() const;
    void setNode(const QString &node);
    bool is_node_Set() const;
    bool is_node_Valid() const;

    QString getCore() const;
    void setCore(const QString &core);
    bool is_core_Set() const;
    bool is_core_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_node;
    bool m_node_isSet;
    bool m_node_isValid;

    QString m_core;
    bool m_core_isSet;
    bool m_core_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIV0_0_40_reservation_core_spec)

#endif // OAIV0_0_40_reservation_core_spec_H
