/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_39_step_task.h
 *
 * 
 */

#ifndef OAIV0_0_39_step_task_H
#define OAIV0_0_39_step_task_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace hm:slurm:client {

class OAIV0_0_39_step_task : public OAIObject {
public:
    OAIV0_0_39_step_task();
    OAIV0_0_39_step_task(QString json);
    ~OAIV0_0_39_step_task() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getDistribution() const;
    void setDistribution(const QString &distribution);
    bool is_distribution_Set() const;
    bool is_distribution_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_distribution;
    bool m_distribution_isSet;
    bool m_distribution_isValid;
};

} // namespace hm:slurm:client

Q_DECLARE_METATYPE(hm:slurm:client::OAIV0_0_39_step_task)

#endif // OAIV0_0_39_step_task_H
