/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory.h
 *
 * 
 */

#ifndef OAIV0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory_H
#define OAIV0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIV0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory : public OAIObject {
public:
    OAIV0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory();
    OAIV0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory(QString json);
    ~OAIV0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getUsed() const;
    void setUsed(const qint64 &used);
    bool is_used_Set() const;
    bool is_used_Valid() const;

    qint64 getAllocated() const;
    void setAllocated(const qint64 &allocated);
    bool is_allocated_Set() const;
    bool is_allocated_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint64 m_used;
    bool m_used_isSet;
    bool m_used_isValid;

    qint64 m_allocated;
    bool m_allocated_isSet;
    bool m_allocated_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIV0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory)

#endif // OAIV0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory_H
