/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_39_qos_limits.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_39_qos_limits::OAIV0_0_39_qos_limits(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_39_qos_limits::OAIV0_0_39_qos_limits() {
    this->initializeModel();
}

OAIV0_0_39_qos_limits::~OAIV0_0_39_qos_limits() {}

void OAIV0_0_39_qos_limits::initializeModel() {

    m_grace_time_isSet = false;
    m_grace_time_isValid = false;

    m_max_isSet = false;
    m_max_isValid = false;

    m_factor_isSet = false;
    m_factor_isValid = false;

    m_min_isSet = false;
    m_min_isValid = false;
}

void OAIV0_0_39_qos_limits::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_39_qos_limits::fromJsonObject(QJsonObject json) {

    m_grace_time_isValid = ::OpenAPI::fromJsonValue(m_grace_time, json[QString("grace_time")]);
    m_grace_time_isSet = !json[QString("grace_time")].isNull() && m_grace_time_isValid;

    m_max_isValid = ::OpenAPI::fromJsonValue(m_max, json[QString("max")]);
    m_max_isSet = !json[QString("max")].isNull() && m_max_isValid;

    m_factor_isValid = ::OpenAPI::fromJsonValue(m_factor, json[QString("factor")]);
    m_factor_isSet = !json[QString("factor")].isNull() && m_factor_isValid;

    m_min_isValid = ::OpenAPI::fromJsonValue(m_min, json[QString("min")]);
    m_min_isSet = !json[QString("min")].isNull() && m_min_isValid;
}

QString OAIV0_0_39_qos_limits::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_39_qos_limits::asJsonObject() const {
    QJsonObject obj;
    if (m_grace_time.isSet()) {
        obj.insert(QString("grace_time"), ::OpenAPI::toJsonValue(m_grace_time));
    }
    if (m_max.isSet()) {
        obj.insert(QString("max"), ::OpenAPI::toJsonValue(m_max));
    }
    if (m_factor_isSet) {
        obj.insert(QString("factor"), ::OpenAPI::toJsonValue(m_factor));
    }
    if (m_min.isSet()) {
        obj.insert(QString("min"), ::OpenAPI::toJsonValue(m_min));
    }
    return obj;
}

OAIV0_0_39_uint32_no_val OAIV0_0_39_qos_limits::getGraceTime() const {
    return m_grace_time;
}
void OAIV0_0_39_qos_limits::setGraceTime(const OAIV0_0_39_uint32_no_val &grace_time) {
    m_grace_time = grace_time;
    m_grace_time_isSet = true;
}

bool OAIV0_0_39_qos_limits::is_grace_time_Set() const{
    return m_grace_time_isSet;
}

bool OAIV0_0_39_qos_limits::is_grace_time_Valid() const{
    return m_grace_time_isValid;
}

OAIV0_0_39_qos_limits_max OAIV0_0_39_qos_limits::getMax() const {
    return m_max;
}
void OAIV0_0_39_qos_limits::setMax(const OAIV0_0_39_qos_limits_max &max) {
    m_max = max;
    m_max_isSet = true;
}

bool OAIV0_0_39_qos_limits::is_max_Set() const{
    return m_max_isSet;
}

bool OAIV0_0_39_qos_limits::is_max_Valid() const{
    return m_max_isValid;
}

double OAIV0_0_39_qos_limits::getFactor() const {
    return m_factor;
}
void OAIV0_0_39_qos_limits::setFactor(const double &factor) {
    m_factor = factor;
    m_factor_isSet = true;
}

bool OAIV0_0_39_qos_limits::is_factor_Set() const{
    return m_factor_isSet;
}

bool OAIV0_0_39_qos_limits::is_factor_Valid() const{
    return m_factor_isValid;
}

OAIV0_0_39_qos_limits_min OAIV0_0_39_qos_limits::getMin() const {
    return m_min;
}
void OAIV0_0_39_qos_limits::setMin(const OAIV0_0_39_qos_limits_min &min) {
    m_min = min;
    m_min_isSet = true;
}

bool OAIV0_0_39_qos_limits::is_min_Set() const{
    return m_min_isSet;
}

bool OAIV0_0_39_qos_limits::is_min_Valid() const{
    return m_min_isValid;
}

bool OAIV0_0_39_qos_limits::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_grace_time.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_max.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_factor_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_min.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_39_qos_limits::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
