/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_40_process_exit_code_verbose.h
 *
 * 
 */

#ifndef OAIV0_0_40_process_exit_code_verbose_H
#define OAIV0_0_40_process_exit_code_verbose_H

#include <QJsonObject>

#include "OAIV0_0_40_process_exit_code_verbose_signal.h"
#include "OAIV0_0_40_uint32_no_val.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace hm:slurm:client {
class OAIV0_0_40_uint32_no_val;
class OAIV0_0_40_process_exit_code_verbose_signal;

class OAIV0_0_40_process_exit_code_verbose : public OAIObject {
public:
    OAIV0_0_40_process_exit_code_verbose();
    OAIV0_0_40_process_exit_code_verbose(QString json);
    ~OAIV0_0_40_process_exit_code_verbose() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<QString> getStatus() const;
    void setStatus(const QList<QString> &status);
    bool is_status_Set() const;
    bool is_status_Valid() const;

    OAIV0_0_40_uint32_no_val getReturnCode() const;
    void setReturnCode(const OAIV0_0_40_uint32_no_val &return_code);
    bool is_return_code_Set() const;
    bool is_return_code_Valid() const;

    OAIV0_0_40_process_exit_code_verbose_signal getSignal() const;
    void setSignal(const OAIV0_0_40_process_exit_code_verbose_signal &signal);
    bool is_signal_Set() const;
    bool is_signal_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<QString> m_status;
    bool m_status_isSet;
    bool m_status_isValid;

    OAIV0_0_40_uint32_no_val m_return_code;
    bool m_return_code_isSet;
    bool m_return_code_isValid;

    OAIV0_0_40_process_exit_code_verbose_signal m_signal;
    bool m_signal_isSet;
    bool m_signal_isValid;
};

} // namespace hm:slurm:client

Q_DECLARE_METATYPE(hm:slurm:client::OAIV0_0_40_process_exit_code_verbose)

#endif // OAIV0_0_40_process_exit_code_verbose_H
