/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per.h
 *
 * 
 */

#ifndef OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_H
#define OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_H

#include <QJsonObject>

#include "OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_account.h"
#include "OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_user.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_account;
class OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_user;

class OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per : public OAIObject {
public:
    OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per();
    OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per(QString json);
    ~OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_account getAccount() const;
    void setAccount(const OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_account &account);
    bool is_account_Set() const;
    bool is_account_Valid() const;

    OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_user getUser() const;
    void setUser(const OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_user &user);
    bool is_user_Set() const;
    bool is_user_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_account m_account;
    bool m_account_isSet;
    bool m_account_isValid;

    OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_user m_user;
    bool m_user_isSet;
    bool m_user_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per)

#endif // OAIV0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_accruing_per_H
