/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_39_assoc_max.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_39_assoc_max::OAIV0_0_39_assoc_max(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_39_assoc_max::OAIV0_0_39_assoc_max() {
    this->initializeModel();
}

OAIV0_0_39_assoc_max::~OAIV0_0_39_assoc_max() {}

void OAIV0_0_39_assoc_max::initializeModel() {

    m_jobs_isSet = false;
    m_jobs_isValid = false;
}

void OAIV0_0_39_assoc_max::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_39_assoc_max::fromJsonObject(QJsonObject json) {

    m_jobs_isValid = ::OpenAPI::fromJsonValue(m_jobs, json[QString("jobs")]);
    m_jobs_isSet = !json[QString("jobs")].isNull() && m_jobs_isValid;
}

QString OAIV0_0_39_assoc_max::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_39_assoc_max::asJsonObject() const {
    QJsonObject obj;
    if (m_jobs.isSet()) {
        obj.insert(QString("jobs"), ::OpenAPI::toJsonValue(m_jobs));
    }
    return obj;
}

OAIV0_0_39_assoc_max_jobs OAIV0_0_39_assoc_max::getJobs() const {
    return m_jobs;
}
void OAIV0_0_39_assoc_max::setJobs(const OAIV0_0_39_assoc_max_jobs &jobs) {
    m_jobs = jobs;
    m_jobs_isSet = true;
}

bool OAIV0_0_39_assoc_max::is_jobs_Set() const{
    return m_jobs_isSet;
}

bool OAIV0_0_39_assoc_max::is_jobs_Valid() const{
    return m_jobs_isValid;
}

bool OAIV0_0_39_assoc_max::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_jobs.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_39_assoc_max::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
