/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_41_openapi_diag_resp_statistics_pending_rpcs_by_hostlist_inner.h
 *
 * Pending RPCs by hostlist
 */

#ifndef OAIV0_0_41_openapi_diag_resp_statistics_pending_rpcs_by_hostlist_inner_H
#define OAIV0_0_41_openapi_diag_resp_statistics_pending_rpcs_by_hostlist_inner_H

#include <QJsonObject>

#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace hm:slurm:client {

class OAIV0_0_41_openapi_diag_resp_statistics_pending_rpcs_by_hostlist_inner : public OAIObject {
public:
    OAIV0_0_41_openapi_diag_resp_statistics_pending_rpcs_by_hostlist_inner();
    OAIV0_0_41_openapi_diag_resp_statistics_pending_rpcs_by_hostlist_inner(QString json);
    ~OAIV0_0_41_openapi_diag_resp_statistics_pending_rpcs_by_hostlist_inner() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getTypeId() const;
    void setTypeId(const qint32 &type_id);
    bool is_type_id_Set() const;
    bool is_type_id_Valid() const;

    QString getMessageType() const;
    void setMessageType(const QString &message_type);
    bool is_message_type_Set() const;
    bool is_message_type_Valid() const;

    QList<QString> getCount() const;
    void setCount(const QList<QString> &count);
    bool is_count_Set() const;
    bool is_count_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_type_id;
    bool m_type_id_isSet;
    bool m_type_id_isValid;

    QString m_message_type;
    bool m_message_type_isSet;
    bool m_message_type_isValid;

    QList<QString> m_count;
    bool m_count_isSet;
    bool m_count_isValid;
};

} // namespace hm:slurm:client

Q_DECLARE_METATYPE(hm:slurm:client::OAIV0_0_41_openapi_diag_resp_statistics_pending_rpcs_by_hostlist_inner)

#endif // OAIV0_0_41_openapi_diag_resp_statistics_pending_rpcs_by_hostlist_inner_H
