/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_39_assoc_max_jobs_per.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_39_assoc_max_jobs_per::OAIV0_0_39_assoc_max_jobs_per(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_39_assoc_max_jobs_per::OAIV0_0_39_assoc_max_jobs_per() {
    this->initializeModel();
}

OAIV0_0_39_assoc_max_jobs_per::~OAIV0_0_39_assoc_max_jobs_per() {}

void OAIV0_0_39_assoc_max_jobs_per::initializeModel() {

    m_wall_clock_isSet = false;
    m_wall_clock_isValid = false;
}

void OAIV0_0_39_assoc_max_jobs_per::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_39_assoc_max_jobs_per::fromJsonObject(QJsonObject json) {

    m_wall_clock_isValid = ::OpenAPI::fromJsonValue(m_wall_clock, json[QString("wall_clock")]);
    m_wall_clock_isSet = !json[QString("wall_clock")].isNull() && m_wall_clock_isValid;
}

QString OAIV0_0_39_assoc_max_jobs_per::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_39_assoc_max_jobs_per::asJsonObject() const {
    QJsonObject obj;
    if (m_wall_clock.isSet()) {
        obj.insert(QString("wall_clock"), ::OpenAPI::toJsonValue(m_wall_clock));
    }
    return obj;
}

OAIV0_0_39_uint32_no_val OAIV0_0_39_assoc_max_jobs_per::getWallClock() const {
    return m_wall_clock;
}
void OAIV0_0_39_assoc_max_jobs_per::setWallClock(const OAIV0_0_39_uint32_no_val &wall_clock) {
    m_wall_clock = wall_clock;
    m_wall_clock_isSet = true;
}

bool OAIV0_0_39_assoc_max_jobs_per::is_wall_clock_Set() const{
    return m_wall_clock_isSet;
}

bool OAIV0_0_39_assoc_max_jobs_per::is_wall_clock_Valid() const{
    return m_wall_clock_isValid;
}

bool OAIV0_0_39_assoc_max_jobs_per::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_wall_clock.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_39_assoc_max_jobs_per::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
