/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_39_nodes_response.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_39_nodes_response::OAIV0_0_39_nodes_response(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_39_nodes_response::OAIV0_0_39_nodes_response() {
    this->initializeModel();
}

OAIV0_0_39_nodes_response::~OAIV0_0_39_nodes_response() {}

void OAIV0_0_39_nodes_response::initializeModel() {

    m_meta_isSet = false;
    m_meta_isValid = false;

    m_errors_isSet = false;
    m_errors_isValid = false;

    m_warnings_isSet = false;
    m_warnings_isValid = false;

    m_nodes_isSet = false;
    m_nodes_isValid = false;
}

void OAIV0_0_39_nodes_response::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_39_nodes_response::fromJsonObject(QJsonObject json) {

    m_meta_isValid = ::OpenAPI::fromJsonValue(m_meta, json[QString("meta")]);
    m_meta_isSet = !json[QString("meta")].isNull() && m_meta_isValid;

    m_errors_isValid = ::OpenAPI::fromJsonValue(m_errors, json[QString("errors")]);
    m_errors_isSet = !json[QString("errors")].isNull() && m_errors_isValid;

    m_warnings_isValid = ::OpenAPI::fromJsonValue(m_warnings, json[QString("warnings")]);
    m_warnings_isSet = !json[QString("warnings")].isNull() && m_warnings_isValid;

    m_nodes_isValid = ::OpenAPI::fromJsonValue(m_nodes, json[QString("nodes")]);
    m_nodes_isSet = !json[QString("nodes")].isNull() && m_nodes_isValid;
}

QString OAIV0_0_39_nodes_response::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_39_nodes_response::asJsonObject() const {
    QJsonObject obj;
    if (m_meta.isSet()) {
        obj.insert(QString("meta"), ::OpenAPI::toJsonValue(m_meta));
    }
    if (m_errors.size() > 0) {
        obj.insert(QString("errors"), ::OpenAPI::toJsonValue(m_errors));
    }
    if (m_warnings.size() > 0) {
        obj.insert(QString("warnings"), ::OpenAPI::toJsonValue(m_warnings));
    }
    if (m_nodes.size() > 0) {
        obj.insert(QString("nodes"), ::OpenAPI::toJsonValue(m_nodes));
    }
    return obj;
}

OAIV0_0_39_meta OAIV0_0_39_nodes_response::getMeta() const {
    return m_meta;
}
void OAIV0_0_39_nodes_response::setMeta(const OAIV0_0_39_meta &meta) {
    m_meta = meta;
    m_meta_isSet = true;
}

bool OAIV0_0_39_nodes_response::is_meta_Set() const{
    return m_meta_isSet;
}

bool OAIV0_0_39_nodes_response::is_meta_Valid() const{
    return m_meta_isValid;
}

QList<OAIV0_0_39_error> OAIV0_0_39_nodes_response::getErrors() const {
    return m_errors;
}
void OAIV0_0_39_nodes_response::setErrors(const QList<OAIV0_0_39_error> &errors) {
    m_errors = errors;
    m_errors_isSet = true;
}

bool OAIV0_0_39_nodes_response::is_errors_Set() const{
    return m_errors_isSet;
}

bool OAIV0_0_39_nodes_response::is_errors_Valid() const{
    return m_errors_isValid;
}

QList<OAIV0_0_39_warning> OAIV0_0_39_nodes_response::getWarnings() const {
    return m_warnings;
}
void OAIV0_0_39_nodes_response::setWarnings(const QList<OAIV0_0_39_warning> &warnings) {
    m_warnings = warnings;
    m_warnings_isSet = true;
}

bool OAIV0_0_39_nodes_response::is_warnings_Set() const{
    return m_warnings_isSet;
}

bool OAIV0_0_39_nodes_response::is_warnings_Valid() const{
    return m_warnings_isValid;
}

QList<OAIV0_0_39_node> OAIV0_0_39_nodes_response::getNodes() const {
    return m_nodes;
}
void OAIV0_0_39_nodes_response::setNodes(const QList<OAIV0_0_39_node> &nodes) {
    m_nodes = nodes;
    m_nodes_isSet = true;
}

bool OAIV0_0_39_nodes_response::is_nodes_Set() const{
    return m_nodes_isSet;
}

bool OAIV0_0_39_nodes_response::is_nodes_Valid() const{
    return m_nodes_isValid;
}

bool OAIV0_0_39_nodes_response::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_meta.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_errors.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_warnings.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_nodes.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_39_nodes_response::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
