/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_39_job_array.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_39_job_array::OAIV0_0_39_job_array(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_39_job_array::OAIV0_0_39_job_array() {
    this->initializeModel();
}

OAIV0_0_39_job_array::~OAIV0_0_39_job_array() {}

void OAIV0_0_39_job_array::initializeModel() {

    m_task_isSet = false;
    m_task_isValid = false;
}

void OAIV0_0_39_job_array::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_39_job_array::fromJsonObject(QJsonObject json) {

    m_task_isValid = ::OpenAPI::fromJsonValue(m_task, json[QString("task")]);
    m_task_isSet = !json[QString("task")].isNull() && m_task_isValid;
}

QString OAIV0_0_39_job_array::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_39_job_array::asJsonObject() const {
    QJsonObject obj;
    if (m_task_isSet) {
        obj.insert(QString("task"), ::OpenAPI::toJsonValue(m_task));
    }
    return obj;
}

QString OAIV0_0_39_job_array::getTask() const {
    return m_task;
}
void OAIV0_0_39_job_array::setTask(const QString &task) {
    m_task = task;
    m_task_isSet = true;
}

bool OAIV0_0_39_job_array::is_task_Set() const{
    return m_task_isSet;
}

bool OAIV0_0_39_job_array::is_task_Valid() const{
    return m_task_isValid;
}

bool OAIV0_0_39_job_array::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_task_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_39_job_array::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
