/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_40_assoc_max_jobs_per.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_40_assoc_max_jobs_per::OAIV0_0_40_assoc_max_jobs_per(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_40_assoc_max_jobs_per::OAIV0_0_40_assoc_max_jobs_per() {
    this->initializeModel();
}

OAIV0_0_40_assoc_max_jobs_per::~OAIV0_0_40_assoc_max_jobs_per() {}

void OAIV0_0_40_assoc_max_jobs_per::initializeModel() {

    m_count_isSet = false;
    m_count_isValid = false;

    m_accruing_isSet = false;
    m_accruing_isValid = false;

    m_submitted_isSet = false;
    m_submitted_isValid = false;

    m_wall_clock_isSet = false;
    m_wall_clock_isValid = false;
}

void OAIV0_0_40_assoc_max_jobs_per::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_40_assoc_max_jobs_per::fromJsonObject(QJsonObject json) {

    m_count_isValid = ::OpenAPI::fromJsonValue(m_count, json[QString("count")]);
    m_count_isSet = !json[QString("count")].isNull() && m_count_isValid;

    m_accruing_isValid = ::OpenAPI::fromJsonValue(m_accruing, json[QString("accruing")]);
    m_accruing_isSet = !json[QString("accruing")].isNull() && m_accruing_isValid;

    m_submitted_isValid = ::OpenAPI::fromJsonValue(m_submitted, json[QString("submitted")]);
    m_submitted_isSet = !json[QString("submitted")].isNull() && m_submitted_isValid;

    m_wall_clock_isValid = ::OpenAPI::fromJsonValue(m_wall_clock, json[QString("wall_clock")]);
    m_wall_clock_isSet = !json[QString("wall_clock")].isNull() && m_wall_clock_isValid;
}

QString OAIV0_0_40_assoc_max_jobs_per::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_40_assoc_max_jobs_per::asJsonObject() const {
    QJsonObject obj;
    if (m_count.isSet()) {
        obj.insert(QString("count"), ::OpenAPI::toJsonValue(m_count));
    }
    if (m_accruing.isSet()) {
        obj.insert(QString("accruing"), ::OpenAPI::toJsonValue(m_accruing));
    }
    if (m_submitted.isSet()) {
        obj.insert(QString("submitted"), ::OpenAPI::toJsonValue(m_submitted));
    }
    if (m_wall_clock.isSet()) {
        obj.insert(QString("wall_clock"), ::OpenAPI::toJsonValue(m_wall_clock));
    }
    return obj;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_max_jobs_per::getCount() const {
    return m_count;
}
void OAIV0_0_40_assoc_max_jobs_per::setCount(const OAIV0_0_40_uint32_no_val &count) {
    m_count = count;
    m_count_isSet = true;
}

bool OAIV0_0_40_assoc_max_jobs_per::is_count_Set() const{
    return m_count_isSet;
}

bool OAIV0_0_40_assoc_max_jobs_per::is_count_Valid() const{
    return m_count_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_max_jobs_per::getAccruing() const {
    return m_accruing;
}
void OAIV0_0_40_assoc_max_jobs_per::setAccruing(const OAIV0_0_40_uint32_no_val &accruing) {
    m_accruing = accruing;
    m_accruing_isSet = true;
}

bool OAIV0_0_40_assoc_max_jobs_per::is_accruing_Set() const{
    return m_accruing_isSet;
}

bool OAIV0_0_40_assoc_max_jobs_per::is_accruing_Valid() const{
    return m_accruing_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_max_jobs_per::getSubmitted() const {
    return m_submitted;
}
void OAIV0_0_40_assoc_max_jobs_per::setSubmitted(const OAIV0_0_40_uint32_no_val &submitted) {
    m_submitted = submitted;
    m_submitted_isSet = true;
}

bool OAIV0_0_40_assoc_max_jobs_per::is_submitted_Set() const{
    return m_submitted_isSet;
}

bool OAIV0_0_40_assoc_max_jobs_per::is_submitted_Valid() const{
    return m_submitted_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_max_jobs_per::getWallClock() const {
    return m_wall_clock;
}
void OAIV0_0_40_assoc_max_jobs_per::setWallClock(const OAIV0_0_40_uint32_no_val &wall_clock) {
    m_wall_clock = wall_clock;
    m_wall_clock_isSet = true;
}

bool OAIV0_0_40_assoc_max_jobs_per::is_wall_clock_Set() const{
    return m_wall_clock_isSet;
}

bool OAIV0_0_40_assoc_max_jobs_per::is_wall_clock_Valid() const{
    return m_wall_clock_isValid;
}

bool OAIV0_0_40_assoc_max_jobs_per::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_count.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_accruing.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_submitted.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_wall_clock.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_40_assoc_max_jobs_per::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
