/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_39_step_nodes.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_39_step_nodes::OAIV0_0_39_step_nodes(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_39_step_nodes::OAIV0_0_39_step_nodes() {
    this->initializeModel();
}

OAIV0_0_39_step_nodes::~OAIV0_0_39_step_nodes() {}

void OAIV0_0_39_step_nodes::initializeModel() {

    m_list_isSet = false;
    m_list_isValid = false;
}

void OAIV0_0_39_step_nodes::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_39_step_nodes::fromJsonObject(QJsonObject json) {

    m_list_isValid = ::OpenAPI::fromJsonValue(m_list, json[QString("list")]);
    m_list_isSet = !json[QString("list")].isNull() && m_list_isValid;
}

QString OAIV0_0_39_step_nodes::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_39_step_nodes::asJsonObject() const {
    QJsonObject obj;
    if (m_list.size() > 0) {
        obj.insert(QString("list"), ::OpenAPI::toJsonValue(m_list));
    }
    return obj;
}

QList<QString> OAIV0_0_39_step_nodes::getList() const {
    return m_list;
}
void OAIV0_0_39_step_nodes::setList(const QList<QString> &list) {
    m_list = list;
    m_list_isSet = true;
}

bool OAIV0_0_39_step_nodes::is_list_Set() const{
    return m_list_isSet;
}

bool OAIV0_0_39_step_nodes::is_list_Valid() const{
    return m_list_isValid;
}

bool OAIV0_0_39_step_nodes::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_list.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_39_step_nodes::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
