/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_39_step_CPU.h
 *
 * 
 */

#ifndef OAIV0_0_39_step_CPU_H
#define OAIV0_0_39_step_CPU_H

#include <QJsonObject>

#include "OAIV0_0_39_step_CPU_requested_frequency.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIV0_0_39_step_CPU_requested_frequency;

class OAIV0_0_39_step_CPU : public OAIObject {
public:
    OAIV0_0_39_step_CPU();
    OAIV0_0_39_step_CPU(QString json);
    ~OAIV0_0_39_step_CPU() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIV0_0_39_step_CPU_requested_frequency getRequestedFrequency() const;
    void setRequestedFrequency(const OAIV0_0_39_step_CPU_requested_frequency &requested_frequency);
    bool is_requested_frequency_Set() const;
    bool is_requested_frequency_Valid() const;

    QString getGovernor() const;
    void setGovernor(const QString &governor);
    bool is_governor_Set() const;
    bool is_governor_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIV0_0_39_step_CPU_requested_frequency m_requested_frequency;
    bool m_requested_frequency_isSet;
    bool m_requested_frequency_isValid;

    QString m_governor;
    bool m_governor_isSet;
    bool m_governor_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIV0_0_39_step_CPU)

#endif // OAIV0_0_39_step_CPU_H
