/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_39_step_statistics_CPU.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_39_step_statistics_CPU::OAIV0_0_39_step_statistics_CPU(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_39_step_statistics_CPU::OAIV0_0_39_step_statistics_CPU() {
    this->initializeModel();
}

OAIV0_0_39_step_statistics_CPU::~OAIV0_0_39_step_statistics_CPU() {}

void OAIV0_0_39_step_statistics_CPU::initializeModel() {

    m_actual_frequency_isSet = false;
    m_actual_frequency_isValid = false;
}

void OAIV0_0_39_step_statistics_CPU::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_39_step_statistics_CPU::fromJsonObject(QJsonObject json) {

    m_actual_frequency_isValid = ::OpenAPI::fromJsonValue(m_actual_frequency, json[QString("actual_frequency")]);
    m_actual_frequency_isSet = !json[QString("actual_frequency")].isNull() && m_actual_frequency_isValid;
}

QString OAIV0_0_39_step_statistics_CPU::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_39_step_statistics_CPU::asJsonObject() const {
    QJsonObject obj;
    if (m_actual_frequency_isSet) {
        obj.insert(QString("actual_frequency"), ::OpenAPI::toJsonValue(m_actual_frequency));
    }
    return obj;
}

qint64 OAIV0_0_39_step_statistics_CPU::getActualFrequency() const {
    return m_actual_frequency;
}
void OAIV0_0_39_step_statistics_CPU::setActualFrequency(const qint64 &actual_frequency) {
    m_actual_frequency = actual_frequency;
    m_actual_frequency_isSet = true;
}

bool OAIV0_0_39_step_statistics_CPU::is_actual_frequency_Set() const{
    return m_actual_frequency_isSet;
}

bool OAIV0_0_39_step_statistics_CPU::is_actual_frequency_Valid() const{
    return m_actual_frequency_isValid;
}

bool OAIV0_0_39_step_statistics_CPU::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_actual_frequency_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_39_step_statistics_CPU::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
