/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_39_qos_limits_max_tres_per.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_39_qos_limits_max_tres_per::OAIV0_0_39_qos_limits_max_tres_per(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_39_qos_limits_max_tres_per::OAIV0_0_39_qos_limits_max_tres_per() {
    this->initializeModel();
}

OAIV0_0_39_qos_limits_max_tres_per::~OAIV0_0_39_qos_limits_max_tres_per() {}

void OAIV0_0_39_qos_limits_max_tres_per::initializeModel() {

    m_account_isSet = false;
    m_account_isValid = false;

    m_job_isSet = false;
    m_job_isValid = false;

    m_node_isSet = false;
    m_node_isValid = false;

    m_user_isSet = false;
    m_user_isValid = false;
}

void OAIV0_0_39_qos_limits_max_tres_per::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_39_qos_limits_max_tres_per::fromJsonObject(QJsonObject json) {

    m_account_isValid = ::OpenAPI::fromJsonValue(m_account, json[QString("account")]);
    m_account_isSet = !json[QString("account")].isNull() && m_account_isValid;

    m_job_isValid = ::OpenAPI::fromJsonValue(m_job, json[QString("job")]);
    m_job_isSet = !json[QString("job")].isNull() && m_job_isValid;

    m_node_isValid = ::OpenAPI::fromJsonValue(m_node, json[QString("node")]);
    m_node_isSet = !json[QString("node")].isNull() && m_node_isValid;

    m_user_isValid = ::OpenAPI::fromJsonValue(m_user, json[QString("user")]);
    m_user_isSet = !json[QString("user")].isNull() && m_user_isValid;
}

QString OAIV0_0_39_qos_limits_max_tres_per::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_39_qos_limits_max_tres_per::asJsonObject() const {
    QJsonObject obj;
    if (m_account.size() > 0) {
        obj.insert(QString("account"), ::OpenAPI::toJsonValue(m_account));
    }
    if (m_job.size() > 0) {
        obj.insert(QString("job"), ::OpenAPI::toJsonValue(m_job));
    }
    if (m_node.size() > 0) {
        obj.insert(QString("node"), ::OpenAPI::toJsonValue(m_node));
    }
    if (m_user.size() > 0) {
        obj.insert(QString("user"), ::OpenAPI::toJsonValue(m_user));
    }
    return obj;
}

QList<OAIV0_0_39_tres> OAIV0_0_39_qos_limits_max_tres_per::getAccount() const {
    return m_account;
}
void OAIV0_0_39_qos_limits_max_tres_per::setAccount(const QList<OAIV0_0_39_tres> &account) {
    m_account = account;
    m_account_isSet = true;
}

bool OAIV0_0_39_qos_limits_max_tres_per::is_account_Set() const{
    return m_account_isSet;
}

bool OAIV0_0_39_qos_limits_max_tres_per::is_account_Valid() const{
    return m_account_isValid;
}

QList<OAIV0_0_39_tres> OAIV0_0_39_qos_limits_max_tres_per::getJob() const {
    return m_job;
}
void OAIV0_0_39_qos_limits_max_tres_per::setJob(const QList<OAIV0_0_39_tres> &job) {
    m_job = job;
    m_job_isSet = true;
}

bool OAIV0_0_39_qos_limits_max_tres_per::is_job_Set() const{
    return m_job_isSet;
}

bool OAIV0_0_39_qos_limits_max_tres_per::is_job_Valid() const{
    return m_job_isValid;
}

QList<OAIV0_0_39_tres> OAIV0_0_39_qos_limits_max_tres_per::getNode() const {
    return m_node;
}
void OAIV0_0_39_qos_limits_max_tres_per::setNode(const QList<OAIV0_0_39_tres> &node) {
    m_node = node;
    m_node_isSet = true;
}

bool OAIV0_0_39_qos_limits_max_tres_per::is_node_Set() const{
    return m_node_isSet;
}

bool OAIV0_0_39_qos_limits_max_tres_per::is_node_Valid() const{
    return m_node_isValid;
}

QList<OAIV0_0_39_tres> OAIV0_0_39_qos_limits_max_tres_per::getUser() const {
    return m_user;
}
void OAIV0_0_39_qos_limits_max_tres_per::setUser(const QList<OAIV0_0_39_tres> &user) {
    m_user = user;
    m_user_isSet = true;
}

bool OAIV0_0_39_qos_limits_max_tres_per::is_user_Set() const{
    return m_user_isSet;
}

bool OAIV0_0_39_qos_limits_max_tres_per::is_user_Valid() const{
    return m_user_isValid;
}

bool OAIV0_0_39_qos_limits_max_tres_per::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_account.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_job.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_node.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_user.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_39_qos_limits_max_tres_per::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
