/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association.h
 *
 * Association limits and options
 */

#ifndef OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_H
#define OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_H

#include <QJsonObject>

#include "OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_priority.h"
#include "OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner.h"
#include "OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpjobs.h"
#include "OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpjobsaccrue.h"
#include "OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs.h"
#include "OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpwall.h"
#include "OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxjobs.h"
#include "OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxjobsaccrue.h"
#include "OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxsubmitjobs.h"
#include "OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxwalldurationperjob.h"
#include "OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_minpriothresh.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpjobs;
class OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpjobsaccrue;
class OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs;
class OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner;
class OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpwall;
class OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxjobs;
class OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxjobsaccrue;
class OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxsubmitjobs;
class OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxwalldurationperjob;
class OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_minpriothresh;
class OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_priority;

class OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association : public OAIObject {
public:
    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association();
    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association(QString json);
    ~OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getComment() const;
    void setComment(const QString &comment);
    bool is_comment_Set() const;
    bool is_comment_Valid() const;

    QString getDefaultqos() const;
    void setDefaultqos(const QString &defaultqos);
    bool is_defaultqos_Set() const;
    bool is_defaultqos_Valid() const;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpjobs getGrpjobs() const;
    void setGrpjobs(const OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpjobs &grpjobs);
    bool is_grpjobs_Set() const;
    bool is_grpjobs_Valid() const;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpjobsaccrue getGrpjobsaccrue() const;
    void setGrpjobsaccrue(const OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpjobsaccrue &grpjobsaccrue);
    bool is_grpjobsaccrue_Set() const;
    bool is_grpjobsaccrue_Valid() const;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs getGrpsubmitjobs() const;
    void setGrpsubmitjobs(const OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs &grpsubmitjobs);
    bool is_grpsubmitjobs_Set() const;
    bool is_grpsubmitjobs_Valid() const;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> getGrptres() const;
    void setGrptres(const QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> &grptres);
    bool is_grptres_Set() const;
    bool is_grptres_Valid() const;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> getGrptresmins() const;
    void setGrptresmins(const QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> &grptresmins);
    bool is_grptresmins_Set() const;
    bool is_grptresmins_Valid() const;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> getGrptresrunmins() const;
    void setGrptresrunmins(const QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> &grptresrunmins);
    bool is_grptresrunmins_Set() const;
    bool is_grptresrunmins_Valid() const;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpwall getGrpwall() const;
    void setGrpwall(const OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpwall &grpwall);
    bool is_grpwall_Set() const;
    bool is_grpwall_Valid() const;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxjobs getMaxjobs() const;
    void setMaxjobs(const OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxjobs &maxjobs);
    bool is_maxjobs_Set() const;
    bool is_maxjobs_Valid() const;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxjobsaccrue getMaxjobsaccrue() const;
    void setMaxjobsaccrue(const OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxjobsaccrue &maxjobsaccrue);
    bool is_maxjobsaccrue_Set() const;
    bool is_maxjobsaccrue_Valid() const;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxsubmitjobs getMaxsubmitjobs() const;
    void setMaxsubmitjobs(const OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxsubmitjobs &maxsubmitjobs);
    bool is_maxsubmitjobs_Set() const;
    bool is_maxsubmitjobs_Valid() const;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> getMaxtresminsperjob() const;
    void setMaxtresminsperjob(const QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> &maxtresminsperjob);
    bool is_maxtresminsperjob_Set() const;
    bool is_maxtresminsperjob_Valid() const;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> getMaxtresrunmins() const;
    void setMaxtresrunmins(const QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> &maxtresrunmins);
    bool is_maxtresrunmins_Set() const;
    bool is_maxtresrunmins_Valid() const;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> getMaxtresperjob() const;
    void setMaxtresperjob(const QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> &maxtresperjob);
    bool is_maxtresperjob_Set() const;
    bool is_maxtresperjob_Valid() const;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> getMaxtrespernode() const;
    void setMaxtrespernode(const QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> &maxtrespernode);
    bool is_maxtrespernode_Set() const;
    bool is_maxtrespernode_Valid() const;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxwalldurationperjob getMaxwalldurationperjob() const;
    void setMaxwalldurationperjob(const OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxwalldurationperjob &maxwalldurationperjob);
    bool is_maxwalldurationperjob_Set() const;
    bool is_maxwalldurationperjob_Valid() const;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_minpriothresh getMinpriothresh() const;
    void setMinpriothresh(const OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_minpriothresh &minpriothresh);
    bool is_minpriothresh_Set() const;
    bool is_minpriothresh_Valid() const;

    QString getParent() const;
    void setParent(const QString &parent);
    bool is_parent_Set() const;
    bool is_parent_Valid() const;

    OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_priority getPriority() const;
    void setPriority(const OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_priority &priority);
    bool is_priority_Set() const;
    bool is_priority_Valid() const;

    QList<QString> getQoslevel() const;
    void setQoslevel(const QList<QString> &qoslevel);
    bool is_qoslevel_Set() const;
    bool is_qoslevel_Valid() const;

    qint32 getFairshare() const;
    void setFairshare(const qint32 &fairshare);
    bool is_fairshare_Set() const;
    bool is_fairshare_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_comment;
    bool m_comment_isSet;
    bool m_comment_isValid;

    QString m_defaultqos;
    bool m_defaultqos_isSet;
    bool m_defaultqos_isValid;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpjobs m_grpjobs;
    bool m_grpjobs_isSet;
    bool m_grpjobs_isValid;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpjobsaccrue m_grpjobsaccrue;
    bool m_grpjobsaccrue_isSet;
    bool m_grpjobsaccrue_isValid;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs m_grpsubmitjobs;
    bool m_grpsubmitjobs_isSet;
    bool m_grpsubmitjobs_isValid;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> m_grptres;
    bool m_grptres_isSet;
    bool m_grptres_isValid;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> m_grptresmins;
    bool m_grptresmins_isSet;
    bool m_grptresmins_isValid;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> m_grptresrunmins;
    bool m_grptresrunmins_isSet;
    bool m_grptresrunmins_isValid;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_grpwall m_grpwall;
    bool m_grpwall_isSet;
    bool m_grpwall_isValid;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxjobs m_maxjobs;
    bool m_maxjobs_isSet;
    bool m_maxjobs_isValid;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxjobsaccrue m_maxjobsaccrue;
    bool m_maxjobsaccrue_isSet;
    bool m_maxjobsaccrue_isValid;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxsubmitjobs m_maxsubmitjobs;
    bool m_maxsubmitjobs_isSet;
    bool m_maxsubmitjobs_isValid;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> m_maxtresminsperjob;
    bool m_maxtresminsperjob_isSet;
    bool m_maxtresminsperjob_isValid;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> m_maxtresrunmins;
    bool m_maxtresrunmins_isSet;
    bool m_maxtresrunmins_isValid;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> m_maxtresperjob;
    bool m_maxtresperjob_isSet;
    bool m_maxtresperjob_isValid;

    QList<OAIV0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner> m_maxtrespernode;
    bool m_maxtrespernode_isSet;
    bool m_maxtrespernode_isValid;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_maxwalldurationperjob m_maxwalldurationperjob;
    bool m_maxwalldurationperjob_isSet;
    bool m_maxwalldurationperjob_isValid;

    OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_minpriothresh m_minpriothresh;
    bool m_minpriothresh_isSet;
    bool m_minpriothresh_isValid;

    QString m_parent;
    bool m_parent_isSet;
    bool m_parent_isValid;

    OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_priority m_priority;
    bool m_priority_isSet;
    bool m_priority_isValid;

    QList<QString> m_qoslevel;
    bool m_qoslevel_isSet;
    bool m_qoslevel_isValid;

    qint32 m_fairshare;
    bool m_fairshare_isSet;
    bool m_fairshare_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association)

#endif // OAIV0_0_41_openapi_users_add_cond_resp_association_condition_association_H
