/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_39_assoc_max_tres_minutes.h
 *
 * 
 */

#ifndef OAIV0_0_39_assoc_max_tres_minutes_H
#define OAIV0_0_39_assoc_max_tres_minutes_H

#include <QJsonObject>

#include "OAIV0_0_39_assoc_max_tres_minutes_per.h"
#include "OAIV0_0_39_tres.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIV0_0_39_assoc_max_tres_minutes_per;
class OAIV0_0_39_tres;

class OAIV0_0_39_assoc_max_tres_minutes : public OAIObject {
public:
    OAIV0_0_39_assoc_max_tres_minutes();
    OAIV0_0_39_assoc_max_tres_minutes(QString json);
    ~OAIV0_0_39_assoc_max_tres_minutes() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIV0_0_39_assoc_max_tres_minutes_per getPer() const;
    void setPer(const OAIV0_0_39_assoc_max_tres_minutes_per &per);
    bool is_per_Set() const;
    bool is_per_Valid() const;

    QList<OAIV0_0_39_tres> getTotal() const;
    void setTotal(const QList<OAIV0_0_39_tres> &total);
    bool is_total_Set() const;
    bool is_total_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIV0_0_39_assoc_max_tres_minutes_per m_per;
    bool m_per_isSet;
    bool m_per_isValid;

    QList<OAIV0_0_39_tres> m_total;
    bool m_total_isSet;
    bool m_total_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIV0_0_39_assoc_max_tres_minutes)

#endif // OAIV0_0_39_assoc_max_tres_minutes_H
