/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_40_qos_limits_max.h
 *
 * 
 */

#ifndef OAIV0_0_40_qos_limits_max_H
#define OAIV0_0_40_qos_limits_max_H

#include <QJsonObject>

#include "OAIV0_0_40_qos_limits_max_active_jobs.h"
#include "OAIV0_0_40_qos_limits_max_jobs.h"
#include "OAIV0_0_40_qos_limits_max_jobs_active_jobs.h"
#include "OAIV0_0_40_qos_limits_max_tres.h"
#include "OAIV0_0_40_qos_limits_max_wall_clock.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIV0_0_40_qos_limits_max_active_jobs;
class OAIV0_0_40_qos_limits_max_tres;
class OAIV0_0_40_qos_limits_max_wall_clock;
class OAIV0_0_40_qos_limits_max_jobs;
class OAIV0_0_40_qos_limits_max_jobs_active_jobs;

class OAIV0_0_40_qos_limits_max : public OAIObject {
public:
    OAIV0_0_40_qos_limits_max();
    OAIV0_0_40_qos_limits_max(QString json);
    ~OAIV0_0_40_qos_limits_max() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIV0_0_40_qos_limits_max_active_jobs getActiveJobs() const;
    void setActiveJobs(const OAIV0_0_40_qos_limits_max_active_jobs &active_jobs);
    bool is_active_jobs_Set() const;
    bool is_active_jobs_Valid() const;

    OAIV0_0_40_qos_limits_max_tres getTres() const;
    void setTres(const OAIV0_0_40_qos_limits_max_tres &tres);
    bool is_tres_Set() const;
    bool is_tres_Valid() const;

    OAIV0_0_40_qos_limits_max_wall_clock getWallClock() const;
    void setWallClock(const OAIV0_0_40_qos_limits_max_wall_clock &wall_clock);
    bool is_wall_clock_Set() const;
    bool is_wall_clock_Valid() const;

    OAIV0_0_40_qos_limits_max_jobs getJobs() const;
    void setJobs(const OAIV0_0_40_qos_limits_max_jobs &jobs);
    bool is_jobs_Set() const;
    bool is_jobs_Valid() const;

    OAIV0_0_40_qos_limits_max_jobs_active_jobs getAccruing() const;
    void setAccruing(const OAIV0_0_40_qos_limits_max_jobs_active_jobs &accruing);
    bool is_accruing_Set() const;
    bool is_accruing_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIV0_0_40_qos_limits_max_active_jobs m_active_jobs;
    bool m_active_jobs_isSet;
    bool m_active_jobs_isValid;

    OAIV0_0_40_qos_limits_max_tres m_tres;
    bool m_tres_isSet;
    bool m_tres_isValid;

    OAIV0_0_40_qos_limits_max_wall_clock m_wall_clock;
    bool m_wall_clock_isSet;
    bool m_wall_clock_isValid;

    OAIV0_0_40_qos_limits_max_jobs m_jobs;
    bool m_jobs_isSet;
    bool m_jobs_isValid;

    OAIV0_0_40_qos_limits_max_jobs_active_jobs m_accruing;
    bool m_accruing_isSet;
    bool m_accruing_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIV0_0_40_qos_limits_max)

#endif // OAIV0_0_40_qos_limits_max_H
