/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_39_stats_rpc_time.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIV0_0_39_stats_rpc_time::OAIV0_0_39_stats_rpc_time(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_39_stats_rpc_time::OAIV0_0_39_stats_rpc_time() {
    this->initializeModel();
}

OAIV0_0_39_stats_rpc_time::~OAIV0_0_39_stats_rpc_time() {}

void OAIV0_0_39_stats_rpc_time::initializeModel() {

    m_total_isSet = false;
    m_total_isValid = false;
}

void OAIV0_0_39_stats_rpc_time::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_39_stats_rpc_time::fromJsonObject(QJsonObject json) {

    m_total_isValid = ::OpenAPI::fromJsonValue(m_total, json[QString("total")]);
    m_total_isSet = !json[QString("total")].isNull() && m_total_isValid;
}

QString OAIV0_0_39_stats_rpc_time::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_39_stats_rpc_time::asJsonObject() const {
    QJsonObject obj;
    if (m_total_isSet) {
        obj.insert(QString("total"), ::OpenAPI::toJsonValue(m_total));
    }
    return obj;
}

qint64 OAIV0_0_39_stats_rpc_time::getTotal() const {
    return m_total;
}
void OAIV0_0_39_stats_rpc_time::setTotal(const qint64 &total) {
    m_total = total;
    m_total_isSet = true;
}

bool OAIV0_0_39_stats_rpc_time::is_total_Set() const{
    return m_total_isSet;
}

bool OAIV0_0_39_stats_rpc_time::is_total_Valid() const{
    return m_total_isValid;
}

bool OAIV0_0_39_stats_rpc_time::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_total_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_39_stats_rpc_time::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
