/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max.h
 *
 * 
 */

#ifndef OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_H
#define OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_H

#include <QJsonObject>

#include "OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs.h"
#include "OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per.h"
#include "OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace hm:slurm:client {
class OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs;
class OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres;
class OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per;

class OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max : public OAIObject {
public:
    OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max();
    OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max(QString json);
    ~OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs getJobs() const;
    void setJobs(const OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs &jobs);
    bool is_jobs_Set() const;
    bool is_jobs_Valid() const;

    OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres getTres() const;
    void setTres(const OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres &tres);
    bool is_tres_Set() const;
    bool is_tres_Valid() const;

    OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per getPer() const;
    void setPer(const OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per &per);
    bool is_per_Set() const;
    bool is_per_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_jobs m_jobs;
    bool m_jobs_isSet;
    bool m_jobs_isValid;

    OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres m_tres;
    bool m_tres_isSet;
    bool m_tres_isValid;

    OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per m_per;
    bool m_per_isSet;
    bool m_per_isValid;
};

} // namespace hm:slurm:client

Q_DECLARE_METATYPE(hm:slurm:client::OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max)

#endif // OAIV0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_H
