/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_40_openapi_meta_slurm_version.h
 *
 * 
 */

#ifndef OAIV0_0_40_openapi_meta_slurm_version_H
#define OAIV0_0_40_openapi_meta_slurm_version_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace hm:slurm:client {

class OAIV0_0_40_openapi_meta_slurm_version : public OAIObject {
public:
    OAIV0_0_40_openapi_meta_slurm_version();
    OAIV0_0_40_openapi_meta_slurm_version(QString json);
    ~OAIV0_0_40_openapi_meta_slurm_version() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getMajor() const;
    void setMajor(const QString &major);
    bool is_major_Set() const;
    bool is_major_Valid() const;

    QString getMicro() const;
    void setMicro(const QString &micro);
    bool is_micro_Set() const;
    bool is_micro_Valid() const;

    QString getMinor() const;
    void setMinor(const QString &minor);
    bool is_minor_Set() const;
    bool is_minor_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_major;
    bool m_major_isSet;
    bool m_major_isValid;

    QString m_micro;
    bool m_micro_isSet;
    bool m_micro_isValid;

    QString m_minor;
    bool m_minor_isSet;
    bool m_minor_isValid;
};

} // namespace hm:slurm:client

Q_DECLARE_METATYPE(hm:slurm:client::OAIV0_0_40_openapi_meta_slurm_version)

#endif // OAIV0_0_40_openapi_meta_slurm_version_H
