/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_40_stats_msg_rpcs_by_user_inner.h
 *
 * user
 */

#ifndef OAIV0_0_40_stats_msg_rpcs_by_user_inner_H
#define OAIV0_0_40_stats_msg_rpcs_by_user_inner_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace hm:slurm:client {

class OAIV0_0_40_stats_msg_rpcs_by_user_inner : public OAIObject {
public:
    OAIV0_0_40_stats_msg_rpcs_by_user_inner();
    OAIV0_0_40_stats_msg_rpcs_by_user_inner(QString json);
    ~OAIV0_0_40_stats_msg_rpcs_by_user_inner() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getUser() const;
    void setUser(const QString &user);
    bool is_user_Set() const;
    bool is_user_Valid() const;

    qint32 getUserId() const;
    void setUserId(const qint32 &user_id);
    bool is_user_id_Set() const;
    bool is_user_id_Valid() const;

    qint64 getCount() const;
    void setCount(const qint64 &count);
    bool is_count_Set() const;
    bool is_count_Valid() const;

    qint64 getAverageTime() const;
    void setAverageTime(const qint64 &average_time);
    bool is_average_time_Set() const;
    bool is_average_time_Valid() const;

    qint64 getTotalTime() const;
    void setTotalTime(const qint64 &total_time);
    bool is_total_time_Set() const;
    bool is_total_time_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_user;
    bool m_user_isSet;
    bool m_user_isValid;

    qint32 m_user_id;
    bool m_user_id_isSet;
    bool m_user_id_isValid;

    qint64 m_count;
    bool m_count_isSet;
    bool m_count_isValid;

    qint64 m_average_time;
    bool m_average_time_isSet;
    bool m_average_time_isValid;

    qint64 m_total_time;
    bool m_total_time_isSet;
    bool m_total_time_isValid;
};

} // namespace hm:slurm:client

Q_DECLARE_METATYPE(hm:slurm:client::OAIV0_0_40_stats_msg_rpcs_by_user_inner)

#endif // OAIV0_0_40_stats_msg_rpcs_by_user_inner_H
