/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_39_job_required.h
 *
 * 
 */

#ifndef OAIV0_0_39_job_required_H
#define OAIV0_0_39_job_required_H

#include <QJsonObject>

#include "OAIV0_0_39_uint64_no_val.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIV0_0_39_uint64_no_val;

class OAIV0_0_39_job_required : public OAIObject {
public:
    OAIV0_0_39_job_required();
    OAIV0_0_39_job_required(QString json);
    ~OAIV0_0_39_job_required() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getCpus() const;
    void setCpus(const qint32 &cpus);
    bool is_cpus_Set() const;
    bool is_cpus_Valid() const;

    OAIV0_0_39_uint64_no_val getMemoryPerCpu() const;
    void setMemoryPerCpu(const OAIV0_0_39_uint64_no_val &memory_per_cpu);
    bool is_memory_per_cpu_Set() const;
    bool is_memory_per_cpu_Valid() const;

    OAIV0_0_39_uint64_no_val getMemoryPerNode() const;
    void setMemoryPerNode(const OAIV0_0_39_uint64_no_val &memory_per_node);
    bool is_memory_per_node_Set() const;
    bool is_memory_per_node_Valid() const;

    qint64 getMemory() const;
    void setMemory(const qint64 &memory);
    bool is_memory_Set() const;
    bool is_memory_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_cpus;
    bool m_cpus_isSet;
    bool m_cpus_isValid;

    OAIV0_0_39_uint64_no_val m_memory_per_cpu;
    bool m_memory_per_cpu_isSet;
    bool m_memory_per_cpu_isValid;

    OAIV0_0_39_uint64_no_val m_memory_per_node;
    bool m_memory_per_node_isSet;
    bool m_memory_per_node_isValid;

    qint64 m_memory;
    bool m_memory_isSet;
    bool m_memory_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIV0_0_39_job_required)

#endif // OAIV0_0_39_job_required_H
