/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_40_openapi_meta_plugin.h
 *
 * 
 */

#ifndef OAIV0_0_40_openapi_meta_plugin_H
#define OAIV0_0_40_openapi_meta_plugin_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace hm:slurm:client {

class OAIV0_0_40_openapi_meta_plugin : public OAIObject {
public:
    OAIV0_0_40_openapi_meta_plugin();
    OAIV0_0_40_openapi_meta_plugin(QString json);
    ~OAIV0_0_40_openapi_meta_plugin() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getType() const;
    void setType(const QString &type);
    bool is_type_Set() const;
    bool is_type_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QString getDataParser() const;
    void setDataParser(const QString &data_parser);
    bool is_data_parser_Set() const;
    bool is_data_parser_Valid() const;

    QString getAccountingStorage() const;
    void setAccountingStorage(const QString &accounting_storage);
    bool is_accounting_storage_Set() const;
    bool is_accounting_storage_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_type;
    bool m_type_isSet;
    bool m_type_isValid;

    QString m_name;
    bool m_name_isSet;
    bool m_name_isValid;

    QString m_data_parser;
    bool m_data_parser_isSet;
    bool m_data_parser_isValid;

    QString m_accounting_storage;
    bool m_accounting_storage_isSet;
    bool m_accounting_storage_isValid;
};

} // namespace hm:slurm:client

Q_DECLARE_METATYPE(hm:slurm:client::OAIV0_0_40_openapi_meta_plugin)

#endif // OAIV0_0_40_openapi_meta_plugin_H
