/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIV0_0_40_assoc_rec_set.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace hm:slurm:client {

OAIV0_0_40_assoc_rec_set::OAIV0_0_40_assoc_rec_set(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIV0_0_40_assoc_rec_set::OAIV0_0_40_assoc_rec_set() {
    this->initializeModel();
}

OAIV0_0_40_assoc_rec_set::~OAIV0_0_40_assoc_rec_set() {}

void OAIV0_0_40_assoc_rec_set::initializeModel() {

    m_comment_isSet = false;
    m_comment_isValid = false;

    m_defaultqos_isSet = false;
    m_defaultqos_isValid = false;

    m_grpjobs_isSet = false;
    m_grpjobs_isValid = false;

    m_grpjobsaccrue_isSet = false;
    m_grpjobsaccrue_isValid = false;

    m_grpsubmitjobs_isSet = false;
    m_grpsubmitjobs_isValid = false;

    m_grptres_isSet = false;
    m_grptres_isValid = false;

    m_grptresmins_isSet = false;
    m_grptresmins_isValid = false;

    m_grptresrunmins_isSet = false;
    m_grptresrunmins_isValid = false;

    m_grpwall_isSet = false;
    m_grpwall_isValid = false;

    m_maxjobs_isSet = false;
    m_maxjobs_isValid = false;

    m_maxjobsaccrue_isSet = false;
    m_maxjobsaccrue_isValid = false;

    m_maxsubmitjobs_isSet = false;
    m_maxsubmitjobs_isValid = false;

    m_maxtresminsperjob_isSet = false;
    m_maxtresminsperjob_isValid = false;

    m_maxtresrunmins_isSet = false;
    m_maxtresrunmins_isValid = false;

    m_maxtresperjob_isSet = false;
    m_maxtresperjob_isValid = false;

    m_maxtrespernode_isSet = false;
    m_maxtrespernode_isValid = false;

    m_maxwalldurationperjob_isSet = false;
    m_maxwalldurationperjob_isValid = false;

    m_minpriothresh_isSet = false;
    m_minpriothresh_isValid = false;

    m_parent_isSet = false;
    m_parent_isValid = false;

    m_priority_isSet = false;
    m_priority_isValid = false;

    m_qoslevel_isSet = false;
    m_qoslevel_isValid = false;

    m_fairshare_isSet = false;
    m_fairshare_isValid = false;
}

void OAIV0_0_40_assoc_rec_set::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIV0_0_40_assoc_rec_set::fromJsonObject(QJsonObject json) {

    m_comment_isValid = ::hm:slurm:client::fromJsonValue(m_comment, json[QString("comment")]);
    m_comment_isSet = !json[QString("comment")].isNull() && m_comment_isValid;

    m_defaultqos_isValid = ::hm:slurm:client::fromJsonValue(m_defaultqos, json[QString("defaultqos")]);
    m_defaultqos_isSet = !json[QString("defaultqos")].isNull() && m_defaultqos_isValid;

    m_grpjobs_isValid = ::hm:slurm:client::fromJsonValue(m_grpjobs, json[QString("grpjobs")]);
    m_grpjobs_isSet = !json[QString("grpjobs")].isNull() && m_grpjobs_isValid;

    m_grpjobsaccrue_isValid = ::hm:slurm:client::fromJsonValue(m_grpjobsaccrue, json[QString("grpjobsaccrue")]);
    m_grpjobsaccrue_isSet = !json[QString("grpjobsaccrue")].isNull() && m_grpjobsaccrue_isValid;

    m_grpsubmitjobs_isValid = ::hm:slurm:client::fromJsonValue(m_grpsubmitjobs, json[QString("grpsubmitjobs")]);
    m_grpsubmitjobs_isSet = !json[QString("grpsubmitjobs")].isNull() && m_grpsubmitjobs_isValid;

    m_grptres_isValid = ::hm:slurm:client::fromJsonValue(m_grptres, json[QString("grptres")]);
    m_grptres_isSet = !json[QString("grptres")].isNull() && m_grptres_isValid;

    m_grptresmins_isValid = ::hm:slurm:client::fromJsonValue(m_grptresmins, json[QString("grptresmins")]);
    m_grptresmins_isSet = !json[QString("grptresmins")].isNull() && m_grptresmins_isValid;

    m_grptresrunmins_isValid = ::hm:slurm:client::fromJsonValue(m_grptresrunmins, json[QString("grptresrunmins")]);
    m_grptresrunmins_isSet = !json[QString("grptresrunmins")].isNull() && m_grptresrunmins_isValid;

    m_grpwall_isValid = ::hm:slurm:client::fromJsonValue(m_grpwall, json[QString("grpwall")]);
    m_grpwall_isSet = !json[QString("grpwall")].isNull() && m_grpwall_isValid;

    m_maxjobs_isValid = ::hm:slurm:client::fromJsonValue(m_maxjobs, json[QString("maxjobs")]);
    m_maxjobs_isSet = !json[QString("maxjobs")].isNull() && m_maxjobs_isValid;

    m_maxjobsaccrue_isValid = ::hm:slurm:client::fromJsonValue(m_maxjobsaccrue, json[QString("maxjobsaccrue")]);
    m_maxjobsaccrue_isSet = !json[QString("maxjobsaccrue")].isNull() && m_maxjobsaccrue_isValid;

    m_maxsubmitjobs_isValid = ::hm:slurm:client::fromJsonValue(m_maxsubmitjobs, json[QString("maxsubmitjobs")]);
    m_maxsubmitjobs_isSet = !json[QString("maxsubmitjobs")].isNull() && m_maxsubmitjobs_isValid;

    m_maxtresminsperjob_isValid = ::hm:slurm:client::fromJsonValue(m_maxtresminsperjob, json[QString("maxtresminsperjob")]);
    m_maxtresminsperjob_isSet = !json[QString("maxtresminsperjob")].isNull() && m_maxtresminsperjob_isValid;

    m_maxtresrunmins_isValid = ::hm:slurm:client::fromJsonValue(m_maxtresrunmins, json[QString("maxtresrunmins")]);
    m_maxtresrunmins_isSet = !json[QString("maxtresrunmins")].isNull() && m_maxtresrunmins_isValid;

    m_maxtresperjob_isValid = ::hm:slurm:client::fromJsonValue(m_maxtresperjob, json[QString("maxtresperjob")]);
    m_maxtresperjob_isSet = !json[QString("maxtresperjob")].isNull() && m_maxtresperjob_isValid;

    m_maxtrespernode_isValid = ::hm:slurm:client::fromJsonValue(m_maxtrespernode, json[QString("maxtrespernode")]);
    m_maxtrespernode_isSet = !json[QString("maxtrespernode")].isNull() && m_maxtrespernode_isValid;

    m_maxwalldurationperjob_isValid = ::hm:slurm:client::fromJsonValue(m_maxwalldurationperjob, json[QString("maxwalldurationperjob")]);
    m_maxwalldurationperjob_isSet = !json[QString("maxwalldurationperjob")].isNull() && m_maxwalldurationperjob_isValid;

    m_minpriothresh_isValid = ::hm:slurm:client::fromJsonValue(m_minpriothresh, json[QString("minpriothresh")]);
    m_minpriothresh_isSet = !json[QString("minpriothresh")].isNull() && m_minpriothresh_isValid;

    m_parent_isValid = ::hm:slurm:client::fromJsonValue(m_parent, json[QString("parent")]);
    m_parent_isSet = !json[QString("parent")].isNull() && m_parent_isValid;

    m_priority_isValid = ::hm:slurm:client::fromJsonValue(m_priority, json[QString("priority")]);
    m_priority_isSet = !json[QString("priority")].isNull() && m_priority_isValid;

    m_qoslevel_isValid = ::hm:slurm:client::fromJsonValue(m_qoslevel, json[QString("qoslevel")]);
    m_qoslevel_isSet = !json[QString("qoslevel")].isNull() && m_qoslevel_isValid;

    m_fairshare_isValid = ::hm:slurm:client::fromJsonValue(m_fairshare, json[QString("fairshare")]);
    m_fairshare_isSet = !json[QString("fairshare")].isNull() && m_fairshare_isValid;
}

QString OAIV0_0_40_assoc_rec_set::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIV0_0_40_assoc_rec_set::asJsonObject() const {
    QJsonObject obj;
    if (m_comment_isSet) {
        obj.insert(QString("comment"), ::hm:slurm:client::toJsonValue(m_comment));
    }
    if (m_defaultqos_isSet) {
        obj.insert(QString("defaultqos"), ::hm:slurm:client::toJsonValue(m_defaultqos));
    }
    if (m_grpjobs.isSet()) {
        obj.insert(QString("grpjobs"), ::hm:slurm:client::toJsonValue(m_grpjobs));
    }
    if (m_grpjobsaccrue.isSet()) {
        obj.insert(QString("grpjobsaccrue"), ::hm:slurm:client::toJsonValue(m_grpjobsaccrue));
    }
    if (m_grpsubmitjobs.isSet()) {
        obj.insert(QString("grpsubmitjobs"), ::hm:slurm:client::toJsonValue(m_grpsubmitjobs));
    }
    if (m_grptres.size() > 0) {
        obj.insert(QString("grptres"), ::hm:slurm:client::toJsonValue(m_grptres));
    }
    if (m_grptresmins.size() > 0) {
        obj.insert(QString("grptresmins"), ::hm:slurm:client::toJsonValue(m_grptresmins));
    }
    if (m_grptresrunmins.size() > 0) {
        obj.insert(QString("grptresrunmins"), ::hm:slurm:client::toJsonValue(m_grptresrunmins));
    }
    if (m_grpwall.isSet()) {
        obj.insert(QString("grpwall"), ::hm:slurm:client::toJsonValue(m_grpwall));
    }
    if (m_maxjobs.isSet()) {
        obj.insert(QString("maxjobs"), ::hm:slurm:client::toJsonValue(m_maxjobs));
    }
    if (m_maxjobsaccrue.isSet()) {
        obj.insert(QString("maxjobsaccrue"), ::hm:slurm:client::toJsonValue(m_maxjobsaccrue));
    }
    if (m_maxsubmitjobs.isSet()) {
        obj.insert(QString("maxsubmitjobs"), ::hm:slurm:client::toJsonValue(m_maxsubmitjobs));
    }
    if (m_maxtresminsperjob.size() > 0) {
        obj.insert(QString("maxtresminsperjob"), ::hm:slurm:client::toJsonValue(m_maxtresminsperjob));
    }
    if (m_maxtresrunmins.size() > 0) {
        obj.insert(QString("maxtresrunmins"), ::hm:slurm:client::toJsonValue(m_maxtresrunmins));
    }
    if (m_maxtresperjob.size() > 0) {
        obj.insert(QString("maxtresperjob"), ::hm:slurm:client::toJsonValue(m_maxtresperjob));
    }
    if (m_maxtrespernode.size() > 0) {
        obj.insert(QString("maxtrespernode"), ::hm:slurm:client::toJsonValue(m_maxtrespernode));
    }
    if (m_maxwalldurationperjob.isSet()) {
        obj.insert(QString("maxwalldurationperjob"), ::hm:slurm:client::toJsonValue(m_maxwalldurationperjob));
    }
    if (m_minpriothresh.isSet()) {
        obj.insert(QString("minpriothresh"), ::hm:slurm:client::toJsonValue(m_minpriothresh));
    }
    if (m_parent_isSet) {
        obj.insert(QString("parent"), ::hm:slurm:client::toJsonValue(m_parent));
    }
    if (m_priority.isSet()) {
        obj.insert(QString("priority"), ::hm:slurm:client::toJsonValue(m_priority));
    }
    if (m_qoslevel.size() > 0) {
        obj.insert(QString("qoslevel"), ::hm:slurm:client::toJsonValue(m_qoslevel));
    }
    if (m_fairshare_isSet) {
        obj.insert(QString("fairshare"), ::hm:slurm:client::toJsonValue(m_fairshare));
    }
    return obj;
}

QString OAIV0_0_40_assoc_rec_set::getComment() const {
    return m_comment;
}
void OAIV0_0_40_assoc_rec_set::setComment(const QString &comment) {
    m_comment = comment;
    m_comment_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_comment_Set() const{
    return m_comment_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_comment_Valid() const{
    return m_comment_isValid;
}

QString OAIV0_0_40_assoc_rec_set::getDefaultqos() const {
    return m_defaultqos;
}
void OAIV0_0_40_assoc_rec_set::setDefaultqos(const QString &defaultqos) {
    m_defaultqos = defaultqos;
    m_defaultqos_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_defaultqos_Set() const{
    return m_defaultqos_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_defaultqos_Valid() const{
    return m_defaultqos_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_rec_set::getGrpjobs() const {
    return m_grpjobs;
}
void OAIV0_0_40_assoc_rec_set::setGrpjobs(const OAIV0_0_40_uint32_no_val &grpjobs) {
    m_grpjobs = grpjobs;
    m_grpjobs_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_grpjobs_Set() const{
    return m_grpjobs_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_grpjobs_Valid() const{
    return m_grpjobs_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_rec_set::getGrpjobsaccrue() const {
    return m_grpjobsaccrue;
}
void OAIV0_0_40_assoc_rec_set::setGrpjobsaccrue(const OAIV0_0_40_uint32_no_val &grpjobsaccrue) {
    m_grpjobsaccrue = grpjobsaccrue;
    m_grpjobsaccrue_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_grpjobsaccrue_Set() const{
    return m_grpjobsaccrue_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_grpjobsaccrue_Valid() const{
    return m_grpjobsaccrue_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_rec_set::getGrpsubmitjobs() const {
    return m_grpsubmitjobs;
}
void OAIV0_0_40_assoc_rec_set::setGrpsubmitjobs(const OAIV0_0_40_uint32_no_val &grpsubmitjobs) {
    m_grpsubmitjobs = grpsubmitjobs;
    m_grpsubmitjobs_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_grpsubmitjobs_Set() const{
    return m_grpsubmitjobs_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_grpsubmitjobs_Valid() const{
    return m_grpsubmitjobs_isValid;
}

QList<OAIV0_0_40_tres> OAIV0_0_40_assoc_rec_set::getGrptres() const {
    return m_grptres;
}
void OAIV0_0_40_assoc_rec_set::setGrptres(const QList<OAIV0_0_40_tres> &grptres) {
    m_grptres = grptres;
    m_grptres_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_grptres_Set() const{
    return m_grptres_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_grptres_Valid() const{
    return m_grptres_isValid;
}

QList<OAIV0_0_40_tres> OAIV0_0_40_assoc_rec_set::getGrptresmins() const {
    return m_grptresmins;
}
void OAIV0_0_40_assoc_rec_set::setGrptresmins(const QList<OAIV0_0_40_tres> &grptresmins) {
    m_grptresmins = grptresmins;
    m_grptresmins_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_grptresmins_Set() const{
    return m_grptresmins_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_grptresmins_Valid() const{
    return m_grptresmins_isValid;
}

QList<OAIV0_0_40_tres> OAIV0_0_40_assoc_rec_set::getGrptresrunmins() const {
    return m_grptresrunmins;
}
void OAIV0_0_40_assoc_rec_set::setGrptresrunmins(const QList<OAIV0_0_40_tres> &grptresrunmins) {
    m_grptresrunmins = grptresrunmins;
    m_grptresrunmins_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_grptresrunmins_Set() const{
    return m_grptresrunmins_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_grptresrunmins_Valid() const{
    return m_grptresrunmins_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_rec_set::getGrpwall() const {
    return m_grpwall;
}
void OAIV0_0_40_assoc_rec_set::setGrpwall(const OAIV0_0_40_uint32_no_val &grpwall) {
    m_grpwall = grpwall;
    m_grpwall_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_grpwall_Set() const{
    return m_grpwall_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_grpwall_Valid() const{
    return m_grpwall_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_rec_set::getMaxjobs() const {
    return m_maxjobs;
}
void OAIV0_0_40_assoc_rec_set::setMaxjobs(const OAIV0_0_40_uint32_no_val &maxjobs) {
    m_maxjobs = maxjobs;
    m_maxjobs_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_maxjobs_Set() const{
    return m_maxjobs_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_maxjobs_Valid() const{
    return m_maxjobs_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_rec_set::getMaxjobsaccrue() const {
    return m_maxjobsaccrue;
}
void OAIV0_0_40_assoc_rec_set::setMaxjobsaccrue(const OAIV0_0_40_uint32_no_val &maxjobsaccrue) {
    m_maxjobsaccrue = maxjobsaccrue;
    m_maxjobsaccrue_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_maxjobsaccrue_Set() const{
    return m_maxjobsaccrue_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_maxjobsaccrue_Valid() const{
    return m_maxjobsaccrue_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_rec_set::getMaxsubmitjobs() const {
    return m_maxsubmitjobs;
}
void OAIV0_0_40_assoc_rec_set::setMaxsubmitjobs(const OAIV0_0_40_uint32_no_val &maxsubmitjobs) {
    m_maxsubmitjobs = maxsubmitjobs;
    m_maxsubmitjobs_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_maxsubmitjobs_Set() const{
    return m_maxsubmitjobs_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_maxsubmitjobs_Valid() const{
    return m_maxsubmitjobs_isValid;
}

QList<OAIV0_0_40_tres> OAIV0_0_40_assoc_rec_set::getMaxtresminsperjob() const {
    return m_maxtresminsperjob;
}
void OAIV0_0_40_assoc_rec_set::setMaxtresminsperjob(const QList<OAIV0_0_40_tres> &maxtresminsperjob) {
    m_maxtresminsperjob = maxtresminsperjob;
    m_maxtresminsperjob_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_maxtresminsperjob_Set() const{
    return m_maxtresminsperjob_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_maxtresminsperjob_Valid() const{
    return m_maxtresminsperjob_isValid;
}

QList<OAIV0_0_40_tres> OAIV0_0_40_assoc_rec_set::getMaxtresrunmins() const {
    return m_maxtresrunmins;
}
void OAIV0_0_40_assoc_rec_set::setMaxtresrunmins(const QList<OAIV0_0_40_tres> &maxtresrunmins) {
    m_maxtresrunmins = maxtresrunmins;
    m_maxtresrunmins_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_maxtresrunmins_Set() const{
    return m_maxtresrunmins_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_maxtresrunmins_Valid() const{
    return m_maxtresrunmins_isValid;
}

QList<OAIV0_0_40_tres> OAIV0_0_40_assoc_rec_set::getMaxtresperjob() const {
    return m_maxtresperjob;
}
void OAIV0_0_40_assoc_rec_set::setMaxtresperjob(const QList<OAIV0_0_40_tres> &maxtresperjob) {
    m_maxtresperjob = maxtresperjob;
    m_maxtresperjob_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_maxtresperjob_Set() const{
    return m_maxtresperjob_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_maxtresperjob_Valid() const{
    return m_maxtresperjob_isValid;
}

QList<OAIV0_0_40_tres> OAIV0_0_40_assoc_rec_set::getMaxtrespernode() const {
    return m_maxtrespernode;
}
void OAIV0_0_40_assoc_rec_set::setMaxtrespernode(const QList<OAIV0_0_40_tres> &maxtrespernode) {
    m_maxtrespernode = maxtrespernode;
    m_maxtrespernode_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_maxtrespernode_Set() const{
    return m_maxtrespernode_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_maxtrespernode_Valid() const{
    return m_maxtrespernode_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_rec_set::getMaxwalldurationperjob() const {
    return m_maxwalldurationperjob;
}
void OAIV0_0_40_assoc_rec_set::setMaxwalldurationperjob(const OAIV0_0_40_uint32_no_val &maxwalldurationperjob) {
    m_maxwalldurationperjob = maxwalldurationperjob;
    m_maxwalldurationperjob_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_maxwalldurationperjob_Set() const{
    return m_maxwalldurationperjob_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_maxwalldurationperjob_Valid() const{
    return m_maxwalldurationperjob_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_rec_set::getMinpriothresh() const {
    return m_minpriothresh;
}
void OAIV0_0_40_assoc_rec_set::setMinpriothresh(const OAIV0_0_40_uint32_no_val &minpriothresh) {
    m_minpriothresh = minpriothresh;
    m_minpriothresh_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_minpriothresh_Set() const{
    return m_minpriothresh_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_minpriothresh_Valid() const{
    return m_minpriothresh_isValid;
}

QString OAIV0_0_40_assoc_rec_set::getParent() const {
    return m_parent;
}
void OAIV0_0_40_assoc_rec_set::setParent(const QString &parent) {
    m_parent = parent;
    m_parent_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_parent_Set() const{
    return m_parent_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_parent_Valid() const{
    return m_parent_isValid;
}

OAIV0_0_40_uint32_no_val OAIV0_0_40_assoc_rec_set::getPriority() const {
    return m_priority;
}
void OAIV0_0_40_assoc_rec_set::setPriority(const OAIV0_0_40_uint32_no_val &priority) {
    m_priority = priority;
    m_priority_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_priority_Set() const{
    return m_priority_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_priority_Valid() const{
    return m_priority_isValid;
}

QList<QString> OAIV0_0_40_assoc_rec_set::getQoslevel() const {
    return m_qoslevel;
}
void OAIV0_0_40_assoc_rec_set::setQoslevel(const QList<QString> &qoslevel) {
    m_qoslevel = qoslevel;
    m_qoslevel_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_qoslevel_Set() const{
    return m_qoslevel_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_qoslevel_Valid() const{
    return m_qoslevel_isValid;
}

qint32 OAIV0_0_40_assoc_rec_set::getFairshare() const {
    return m_fairshare;
}
void OAIV0_0_40_assoc_rec_set::setFairshare(const qint32 &fairshare) {
    m_fairshare = fairshare;
    m_fairshare_isSet = true;
}

bool OAIV0_0_40_assoc_rec_set::is_fairshare_Set() const{
    return m_fairshare_isSet;
}

bool OAIV0_0_40_assoc_rec_set::is_fairshare_Valid() const{
    return m_fairshare_isValid;
}

bool OAIV0_0_40_assoc_rec_set::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_comment_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_defaultqos_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_grpjobs.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_grpjobsaccrue.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_grpsubmitjobs.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_grptres.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_grptresmins.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_grptresrunmins.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_grpwall.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_maxjobs.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_maxjobsaccrue.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_maxsubmitjobs.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_maxtresminsperjob.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_maxtresrunmins.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_maxtresperjob.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_maxtrespernode.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_maxwalldurationperjob.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_minpriothresh.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_parent_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_priority.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_qoslevel.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_fairshare_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIV0_0_40_assoc_rec_set::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace hm:slurm:client
