/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_39_step_statistics_energy.h
 *
 * 
 */

#ifndef OAIV0_0_39_step_statistics_energy_H
#define OAIV0_0_39_step_statistics_energy_H

#include <QJsonObject>

#include "OAIV0_0_39_uint64_no_val.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIV0_0_39_uint64_no_val;

class OAIV0_0_39_step_statistics_energy : public OAIObject {
public:
    OAIV0_0_39_step_statistics_energy();
    OAIV0_0_39_step_statistics_energy(QString json);
    ~OAIV0_0_39_step_statistics_energy() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIV0_0_39_uint64_no_val getConsumed() const;
    void setConsumed(const OAIV0_0_39_uint64_no_val &consumed);
    bool is_consumed_Set() const;
    bool is_consumed_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIV0_0_39_uint64_no_val m_consumed;
    bool m_consumed_isSet;
    bool m_consumed_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIV0_0_39_step_statistics_energy)

#endif // OAIV0_0_39_step_statistics_energy_H
