/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIV0_0_40_openapi_meta_slurm.h
 *
 * 
 */

#ifndef OAIV0_0_40_openapi_meta_slurm_H
#define OAIV0_0_40_openapi_meta_slurm_H

#include <QJsonObject>

#include "OAIV0_0_40_openapi_meta_slurm_version.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIV0_0_40_openapi_meta_slurm_version;

class OAIV0_0_40_openapi_meta_slurm : public OAIObject {
public:
    OAIV0_0_40_openapi_meta_slurm();
    OAIV0_0_40_openapi_meta_slurm(QString json);
    ~OAIV0_0_40_openapi_meta_slurm() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIV0_0_40_openapi_meta_slurm_version getVersion() const;
    void setVersion(const OAIV0_0_40_openapi_meta_slurm_version &version);
    bool is_version_Set() const;
    bool is_version_Valid() const;

    QString getRelease() const;
    void setRelease(const QString &release);
    bool is_release_Set() const;
    bool is_release_Valid() const;

    QString getCluster() const;
    void setCluster(const QString &cluster);
    bool is_cluster_Set() const;
    bool is_cluster_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIV0_0_40_openapi_meta_slurm_version m_version;
    bool m_version_isSet;
    bool m_version_isValid;

    QString m_release;
    bool m_release_isSet;
    bool m_release_isValid;

    QString m_cluster;
    bool m_cluster_isSet;
    bool m_cluster_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIV0_0_40_openapi_meta_slurm)

#endif // OAIV0_0_40_openapi_meta_slurm_H
